---
- block:
    - name: create the docker-storage config file
      template:
        src: docker-storage-setup-overlayfs.j2
        dest: /etc/sysconfig/docker-storage-setup
        owner: root
        group: root
        mode: 0644

    - name: Check if docker is running
      command: systemctl status {{ openshift_docker_service_name }}
      register: docker_running
      ignore_errors: yes

    - name: restart docker after storage configuration
      become: yes
      systemd:
        name: "{{ openshift_docker_service_name }}"
        state: restarted
      register: l_docker_restart_docker_in_storage_setup_result
      until: not (l_docker_restart_docker_in_storage_setup_result is failed)
      retries: 3
      delay: 30
      when:
        - not openshift_use_crio_only|default(None)
        - docker_running.rc == 0
  when:
    - openshift_configure_container_storage == true 

