---

- name: "Set defaults"
  set_fact:
    processed_namespace: "{{ target_namespace | default('') }}"

- name: Empty namespace param when not needed
  set_fact:
    namespace_param: "{{ (processed_namespace|length > 0) | ternary('-n ' + processed_namespace, '') }}"

- name: "Apply label {{ label }} to object {{ target_object }}"
  command: >
    oc label --overwrite {{ target_object }} {{ target_name }} {{ label }} {{ namespace_param }}
  when:
  - target_object is defined
  - target_object|trim != ''
  - target_name is defined
  - target_name|trim != ''
  - label is defined
  - label| trim != ''
