---

openshift_docker_service_name: "docker"

openshift_configure_container_storage: true

# container-storage-setup
openshift_container_storage_setup:
  docker_dev: "/dev/sdb"
  docker_vg: "docker-vol"
  docker_data_size: "95%VG"
  docker_dm_basesize: "3G"
  container_root_lv_name: "dockerlv"
  container_root_lv_mount_path: "/var/lib/docker"



